name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master  # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code using the latest actions/checkout version (v3)
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      # Set up AWS credentials using the latest aws-actions/configure-aws-credentials version (v2)
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2  # Updated to v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify the AWS region

      # Install dependencies (e.g., from requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Package the Lambda function code into a ZIP file
      - name: Package Lambda function
        run: |
          zip -r lambda_function.zip .

      # Deploy the Lambda function using AWS CLI
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name your_lambda_function_name --zip-file fileb://lambda_function.zip
